// Builds IC3D, the world-building kit served with community games: joins engine/src/*.js (in name order) into
// engine/ic3d.js, minifies it, and writes lib/engineSource.js, which lib/creationAI.js inlines into games that use it.
// Runs before `next build` (prebuild) and `next dev` (predev); the output is committed too.
import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const src = path.join(root, 'engine/src');
const files = fs.readdirSync(src).filter((f) => f.endsWith('.js')).sort();
const joined = files.map((f) => `// ---- ${f}\n${fs.readFileSync(path.join(src, f), 'utf8')}`).join('\n');
fs.writeFileSync(path.join(root, 'engine/ic3d.js'), joined);

let code = joined;
try {
  const require = createRequire(import.meta.url);
  const { minify } = require('next/dist/compiled/terser');
  const out = await minify(joined, { module: true, compress: { passes: 2 }, mangle: true, format: { comments: false } });
  code = out.code;
} catch (err) {
  console.warn('engine: not minified:', err.message);
}
// the source sits inside a <script> element when served
code = code.replace(/<\/script/gi, '<\\/script');
const version = Number((joined.match(/const VERSION = (\d+);/) || [])[1] || 1);
fs.writeFileSync(
  path.join(root, 'lib/engineSource.js'),
  `// Generated by scripts/build-engine.mjs from engine/src. Do not edit.\nexport const ENGINE_VERSION = ${version};\nexport const ENGINE_SOURCE = ${JSON.stringify(code)};\n`
);
console.log(`engine: IC3D v${version}, ${files.length} files, ${(joined.length / 1024).toFixed(0)} KB -> ${(code.length / 1024).toFixed(0)} KB`);
